[package]
name = "conject"
version = "0.5.0"
edition = "2024"
description = "Zero cost dependency injection module"
rust-version = "1.85"
homepage = "https://github.com/nicolascotton/conject"
keywords = ["dependency", "injection", "dependency-injection", "ioc"]
license = "MIT"
readme = "./README.md"
repository = "https://github.com/nicolascotton/conject"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
conject-macro = { path = "../conject-macro", version = "0.5.0", optional = true }
const-fnv1a-hash = "1"
    
[dev-dependencies]
trybuild = "1"
conject-macro = { path = "../conject-macro" }
tokio = { version = "1", features = ["macros", "rt"] }
tokio-test = "0.4"

[features]
default = ["macro"]
macro = ["dep:conject-macro"]
alloc = []
std = ["alloc"]
env = ["std", "conject-macro?/env"]
